### get all relay tasks
GET http://127.0.0.1:8000/api/relay HTTP/1.1
Authorization: Basic admin:admin

### create relay pull task
POST http://127.0.0.1:8000/api/relay/pull HTTP/1.1
Authorization: Basic admin:admin 
Content-Type: application/x-www-form-urlencoded

app=live
&name=bbb
&url=rtmp://192.168.0.2/live/bbb

### create relay push task
POST http://127.0.0.1:8000/api/relay/push HTTP/1.1
Authorization: Basic admin:admin 
Content-Type: application/x-www-form-urlencoded

app=live
&name=bbb
&url=rtmp://192.168.0.2/live/bbb2


### create relay task
POST http://127.0.0.1:8000/api/relay/task HTTP/1.1
Authorization: Basic admin:admin 
Content-Type: application/x-www-form-urlencoded

path=rtmp://192.168.0.2/live/bbb
&url=rtmp://127.0.0.1/live/bbb

### delete relay task
DELETE http://127.0.0.1:8000/api/relay/N3MKMPHU HTTP/1.1
Authorization: Basic admin:admin 
