// @ts-check
//
//  Created by Chen Mingliang on 24/11/28.
//  illuspas@msn.com
//  Copyright (c) 2023 NodeMedia. All rights reserved.
//

const EventEmitter = require("node:events");

/**
 * @typedef {import("../store/lightweight_store.js")} LightweightStore
 */

/**
 * @typedef {import("../server/relay_server.js")} NodeRelayServer
 */

/**
 * @typedef {import("../server/record_server.js")} NodeRecordServer
 */

/**
 * @typedef {import("../server/broadcast_server.js")} BroadcastServer
 */

/**
 * @typedef {import("../session/base_session.js")} BaseSession
 */

/**
 * @typedef {object} TlsConfig - TLS listener options (RTMPS / HTTPS)
 * @property {number} [port] - Listen port
 * @property {string} [key] - Path to the private key PEM file
 * @property {string} [cert] - Path to the certificate PEM file
 */

/**
 * @typedef {object} JwtUser - Admin API user credentials (password is a scrypt hash)
 * @property {string} username - Login name
 * @property {string} password - scrypt hash of the login password
 * @property {string} role - Authorization role, e.g. "admin"
 */

/**
 * @typedef {object} JwtConfig - Admin API JWT authentication options
 * @property {string} [secret] - Signing secret (auto-generated by the CLI when empty)
 * @property {string} [expiresIn] - Access token TTL, e.g. "24h"
 * @property {string} [refreshExpiresIn] - Refresh token TTL, e.g. "7d"
 * @property {string} [algorithm] - Signing algorithm, default HS256
 * @property {Array<JwtUser>} [users] - Accounts allowed to log in to the admin API
 */

/**
 * @typedef {object} AuthConfig - Stream publish/play authentication
 * @property {boolean} [play] - Require signed URLs for playback
 * @property {boolean} [publish] - Require signed URLs for publishing
 * @property {string} [secret] - Shared secret for signed URLs
 * @property {JwtConfig} [jwt] - Enables the admin API when present
 */

/**
 * @typedef {object} RecordConfig - FLV recording options
 * @property {boolean} [auto] - Record every published stream; default true
 * @property {string} [path] - Directory root for recordings
 */

/**
 * @typedef {object} StoreConfig - Persistent JSON store options
 * @property {string} [path] - Store directory, default "./data"
 * @property {number} [flushInterval] - Ms between disk flushes
 * @property {number} [maxOps] - Max writes buffered before a flush
 * @property {boolean} [pretty] - Indent persisted JSON
 * @property {string} [durability] - Flush aggressiveness profile
 * @property {number} [maxHistory] - Max retained stream history entries
 */

/**
 * @typedef {object} StaticConfig - Static file serving over HTTP
 * @property {string} [router] - URL prefix to mount, e.g. "/public"
 * @property {string} [root] - Directory root to serve
 */

/**
 * @typedef {object} NmsConfig - Full server configuration, loaded once at startup.
 * All sections are optional; servers skip listeners whose port is unset.
 * @property {string} [bind] - Listen address for all listeners
 * @property {{port?: number}} [rtmp] - Plain RTMP listener
 * @property {TlsConfig} [rtmps] - RTMP over TLS listener
 * @property {{port?: number}} [http] - HTTP-FLV / WS-FLV listener
 * @property {TlsConfig} [https] - HTTPS-FLV / WSS-FLV listener
 * @property {RecordConfig} [record] - FLV recording
 * @property {StoreConfig} [store] - Persistent JSON store
 * @property {StaticConfig} [static] - Static file serving over HTTP
 * @property {AuthConfig} [auth] - Stream and admin API authentication
 * @property {{url?: string}} [notify] - Webhook receiver for stream events
 */

const Context = {
  /**
   * Server configuration, assigned by the NodeMediaServer constructor.
   * @type {NmsConfig}
   */
  config: {},

  /**
   * Optional path of the config file the running instance was loaded from
   * (set by the CLI entry). When present, password changes are persisted to it.
   * @type {string|null}
   */
  configFile: null,

  /**
   * All active connections indexed by session id, regardless of protocol
   * (RTMP, HTTP-FLV, WS-FLV, RTSP, record, relay client).
   * @type {Map<number, BaseSession>}
   */
  sessions: new Map(),

  /**
   * Live streams indexed by stream path; each publisher (RTMP/RTSP/FLV/record
   * session) registers its BroadcastServer here on publish.
   * @type {Map<string, BroadcastServer>}
   */
  broadcasts: new Map(),

  /**
   * Persistent JSON store (relay tasks, record metadata, stream history).
   * Assigned by the NodeMediaServer constructor once the store is created.
   * @type {LightweightStore | null}
   */
  store: null,

  /**
   * Relay task manager, exposed for API access.
   * Assigned by the NodeMediaServer constructor.
   * @type {NodeRelayServer | null}
   */
  relayServer: null,

  /**
   * Record manager, exposed for API access (manual start/stop recording).
   * Assigned by the NodeMediaServer constructor.
   * @type {NodeRecordServer | null}
   */
  recordServer: null,

  /**
   * Cumulative streaming network traffic (bytes) over the process lifetime.
   * Accumulated by every publisher/player session next to its own counters;
   * record sessions (file writes) are excluded.
   * @type {{inBytes: number, outBytes: number}}
   */
  networkStats: { inBytes: 0, outBytes: 0 },

  eventEmitter: new EventEmitter()
};

module.exports = Context;
